### ISSUE TITLE
asadmin deploy: upload parameter missing

### ISSUE THREAD

**Issue by nuukular** [eskatos/asadmin#15]
I tried to use the asadmin-maven-plugin to deploy an application over ssh to a clustered glassfish environment. In order to do so I need to set the upload parameter to true. However, I could not find a way to do this. 
I tried setting <upload>true</upload> in the configuration section, however, this seems to be ignored. After having a look at the code, I get the feeling that this is not currently supported.
Is there a way to set the upload property?

**Comment by eskatos** [comment]
Yes, the upload parameter is not yet supported.
I just commited an attempt at supporting it in a08f40c
You can try the master branch.

**Comment by nuukular** [comment]
I tried the master branch, however I haven't been very successful. Deployment fails with a NullPointerException.

[ERROR] Failed to execute goal org.codeartisans.asadmin:asadmin-maven-plugin:0.10-SNAPSHOT:deploy (default-cli) on project com.project.ear: Execution default-cli of goal org.codeartisans.asadmin:asadmin-maven-plugin:0.10-SNAPSHOT:deploy failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codeartisans.asadmin:asadmin-maven-plugin:0.10-SNAPSHOT:deploy (default-cli) on project com.project.ear: Execution default-cli of goal org.codeartisans.asadmin:asadmin-maven-plugin:0.10-SNAPSHOT:deploy failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.codeartisans.asadmin:asadmin-maven-plugin:0.10-SNAPSHOT:deploy failed.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
Caused by: java.lang.NullPointerException
    at org.n0pe.mojo.asadmin.DeployMojo.getAsCommandList(DeployMojo.java:62)
    at org.n0pe.mojo.asadmin.AbstractAsadminMojo.execute(AbstractAsadminMojo.java:155)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    ... 20 more
[ERROR]

**Comment by eskatos** [comment]
Oops. Should be fixed now.

**Comment by nuukular** [comment]
Thank you. The NPE seems to be fixed. After a quick test, this seems to be all good.

**Comment by eskatos** [comment]
Thanks for reporting back nuukular.
I'll close the issue when I'll roll a new release. Can you live without a release for now?

**Comment by nuukular** [comment]
Yes, I think we could work around that. However, we would greatly appreciate a release in the near future.

**Comment by eskatos** [comment]
Sure, once we'll have solved current issues I'll roll a release.
